name: support_agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - setuptools
  - wheel
  - psutil
  - readline
  - ncurses
  - tk
  - tornado
  - zlib
  - sqlite
  - xz
  - libffi
  - openssl
  - ca-certificates
  - pip:
      # - websockets==11.0
      - websocket-client==1.8.0
      - aenum==3.1.16
      - ag2==0.9.2
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.9
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - asgiref==3.8.1
      - asyncer==0.0.8
      - attrs==25.3.0
      - autogen==0.9.2
      - autogen-agentchat==0.6.1
      - autogen-core==0.6.1
      - autogen-ext==0.6.1
      - backoff==2.2.1
      - bcrypt==4.3.0
      - blinker==1.9.0
      - build==1.2.2.post1
      - cachetools==5.5.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - chromadb==1.0.12
      - click==8.2.1
      - coloredlogs==15.0.1
      - dataclasses-json==0.6.7
      - deepgram-sdk==4.1.0
      - deprecation==2.1.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.7.0
      - docker==7.1.0
      - durationpy==0.10
      - email-validator==2.2.0
      - fastapi==0.115.9
      - fastapi-cli==0.0.7
      - filelock==3.18.0
      - flask==3.1.1
      - flask-cors==6.0.0
      - flask-sock==0.7.0
      - flatbuffers==25.2.10
      - frozenlist==1.6.2
      - fsspec==2025.5.1
      - google-auth==2.40.3
      - googleapis-common-protos==1.70.0
      - grpcio==1.70.0
      - gtfs-realtime-bindings==1.0.0
      - h11==0.16.0
      - h2==4.2.0
      - hf-xet==1.1.3
      - hpack==4.1.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.32.4
      - humanfriendly==10.0
      - hypercorn==0.17.3
      - hyperframe==6.1.0
      - idna==3.10
      - importlib-resources==6.5.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.10.0
      - joblib==1.5.1
      - jotform==1.2
      - jsonref==1.1.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kubernetes==32.0.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - mmh3==5.1.0
      - mpmath==1.3.0
      - multidict==6.4.4
      - mypy-extensions==1.1.0
      - networkx==3.5
      - numpy==2.2.6
      - oauthlib==3.2.2
      - onnxruntime==1.22.0
      - openai==1.84.0
      - opentelemetry-api==1.34.0
      - opentelemetry-exporter-otlp-proto-common==1.34.0
      - opentelemetry-exporter-otlp-proto-grpc==1.34.0
      - opentelemetry-instrumentation==0.55b0
      - opentelemetry-instrumentation-asgi==0.55b0
      - opentelemetry-instrumentation-fastapi==0.55b0
      - opentelemetry-proto==1.34.0
      - opentelemetry-sdk==1.34.0
      - opentelemetry-semantic-conventions==0.55b0
      - opentelemetry-util-http==0.55b0
      - orjson==3.10.18
      - overrides==7.7.0
      - pandas==2.3.0
      - pillow==11.2.1
      - posthog==4.2.0
      - priority==2.0.0
      - propcache==0.3.1
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pydantic-extra-types==2.10.5
      - pydantic-settings==2.9.1
      - pypika==0.48.9
      - pyproj==3.7.1
      - pyproject-hooks==1.2.0
      - python-dotenv==1.1.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - quart==0.20.0
      - quart-cors==0.8.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - rich-toolkit==0.14.7
      - rpds-py==0.25.1
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - sentence-transformers==4.1.0
      - shellingham==1.5.4
      - simple-websocket==1.1.0
      - sniffio==1.3.1
      - starlette==0.45.3
      - sympy==1.14.0
      - tenacity==9.1.2
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - torch==2.7.1
      - tqdm==4.67.1
      - transformers==4.52.4
      - typer==0.16.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - ujson==5.10.0
      - urllib3==2.4.0
      - uvicorn==0.34.3
      - uvloop==0.21.0
      - watchfiles==1.0.5
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - wsproto==1.2.0
      - yarl==1.20.0
      - pydub