name: support_agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - setuptools
  - wheel
  - psutil
  - readline
  - ncurses
  - tk
  - tornado
  - zlib
  - sqlite
  - xz
  - libffi
  - openssl
  - ca-certificates
  - pip:
      - websockets==11.0
      - websocket-client
      - aenum
      - ag2
      - aiofiles
      - aiohappyeyeballs
      - aiohttp
      - aiosignal
      - annotated-types
      - anyio
      - asgiref
      - asyncer
      - attrs
      - autogen
      - autogen-agentchat
      - autogen-core
      - autogen-ext
      - backoff
      - bcrypt
      - blinker
      - build
      - cachetools
      - certifi
      - charset-normalizer
      - chromadb
      - click
      - coloredlogs
      - dataclasses-json
      - deepgram-sdk
      - deprecation
      - diskcache
      - distro
      - dnspython
      - docker
      - durationpy
      - email-validator
      - fastapi
      - fastapi-cli
      - filelock
      - flask
      - flask-cors
      - flask-sock
      - flatbuffers
      - frozenlist
      - fsspec
      - google-auth
      - googleapis-common-protos
      - grpcio
      - gtfs-realtime-bindings
      - h11
      - h2
      - hf-xet
      - hpack
      - httpcore
      - httptools
      - httpx
      - huggingface-hub
      - humanfriendly
      - hypercorn
      - hyperframe
      - idna
      - importlib-resources
      - itsdangerous
      - jinja2
      - jiter
      - joblib
      - jotform
      - jsonref
      - jsonschema
      - jsonschema-specifications
      - kubernetes
      - markdown-it-py
      - markupsafe
      - marshmallow
      - mdurl
      - mmh3
      - mpmath
      - multidict
      - mypy-extensions
      - networkx
      - numpy
      - oauthlib
      - onnxruntime
      - openai
      - opentelemetry-api
      - opentelemetry-exporter-otlp-proto-common
      - opentelemetry-exporter-otlp-proto-grpc
      - opentelemetry-instrumentation
      - opentelemetry-instrumentation-asgi
      - opentelemetry-instrumentation-fastapi
      - opentelemetry-proto
      - opentelemetry-sdk
      - opentelemetry-semantic-conventions
      - opentelemetry-util-http
      - orjson
      - overrides
      - pandas
      - pillow
      - posthog
      - priority
      - propcache
      - protobuf
      - pyasn1
      - pyasn1-modules
      - pydantic
      - pydantic-core
      - pydantic-extra-types
      - pydantic-settings
      - pypika
      - pyproj
      - pyproject-hooks
      - python-dotenv
      - python-multipart
      - pytz
      - pyyaml
      - quart
      - quart-cors
      - referencing
      - regex
      - requests
      - requests-oauthlib
      - rich
      - rich-toolkit
      - rpds-py
      - rsa
      - safetensors
      - scikit-learn
      - scipy
      - sentence-transformers
      - shellingham
      - simple-websocket
      - sniffio
      - starlette
      - sympy
      - tenacity
      - termcolor
      - threadpoolctl
      - tiktoken
      - tokenizers
      - torch
      - tqdm
      - transformers
      - typer
      - typing-inspect
      - typing-inspection
      - tzdata
      - ujson
      - urllib3
      - uvicorn
      - uvloop
      - watchfiles
      - werkzeug
      - wrapt
      - wsproto
      - yarl
      - pydub
      - sounddevice
